source "https://rubygems.org"

gem 'github-pages'
# this gem provides regeneration support improvements on Windows
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem "jekyll"

group :jekyll_plugins do
    gem "jekyll-feed"
    gem "jekyll-mentions"
    gem "webrick"
    gem "jekyll-redirect-from"
    gem "jekyll-sitemap"
    gem "jekyll-avatar"
    gem "jemoji"
  end